R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
            //Unarmed
			"Lada_Civ_04",
            "CUP_C_Datsun",
			"ivory_challenger_marked",
			"ivory_challenger_marked_norb",
			"ivory_challenger_marked_classic",
			"ivory_challenger_unmarked",
			"ivory_challenger_unmarked_norb",
			"ivory_challenger_slicktop",
			"ivory_challenger_slicktop_norb",
			"ivory_challenger_slicktop_classic",
			"ivory_charger_marked",
			"ivory_charger_marked_norb",
			"ivory_charger_marked_classic",
			"ivory_charger_unmarked",
			"ivory_charger_unmarked_norb",
			"ivory_charger_slicktop",
			"ivory_charger_slicktop_norb",
			"ivory_charger_slicktop_classic",
			"ivory_cv_marked",
			"ivory_cv_marked_norb",
			"ivory_cv_marked_classic",
			"ivory_cv_unmarked",
			"ivory_cv_unmarked_norb",
			"ivory_cv_slicktop",
			"ivory_cv_slicktop_norb",
			"ivory_cv_slicktop_classic",
			"ivory_evox_marked",
			"ivory_evox_marked_norb",
			"ivory_evox_marked_classic",
			"ivory_evox_unmarked",
			"ivory_evox_unmarked_norb",
			"ivory_evox_slicktop",
			"ivory_evox_slicktop_norb",
			"ivory_evox_slicktop_classic",
			"ivory_isf_marked",
			"ivory_isf_marked_norb",
			"ivory_isf_marked_classic",
			"ivory_isf_unmarked",
			"ivory_isf_unmarked_norb",
			"ivory_isf_slicktop",
			"ivory_isf_slicktop_norb",
			"ivory_isf_slicktop_classic",
			"ivory_m3_marked",
			"ivory_m3_marked_norb",
			"ivory_m3_marked_classic",
			"ivory_m3_unmarked",
			"ivory_m3_unmarked_norb",
			"ivory_m3_slicktop",
			"ivory_m3_slicktop_norb",
			"ivory_m3_slicktop_classic",
			"ivory_prius_marked",
			"ivory_prius_marked_norb",
			"ivory_prius_marked_classic",
			"ivory_prius_unmarked",
			"ivory_prius_unmarked_norb",
			"ivory_prius_slicktop",
			"ivory_prius_slicktop_norb",
			"ivory_prius_slicktop_classic",
			"ivory_rev_marked",
			"ivory_rev_marked_norb",
			"ivory_rev_marked_classic",
			"ivory_rev_unmarked",
			"ivory_rev_unmarked_norb",
			"ivory_rev_slicktop",
			"ivory_rev_slicktop_norb",
			"ivory_rev_slicktop_classic",
			"ivory_rs4_marked",
			"ivory_rs4_marked_norb",
			"ivory_rs4_marked_classic",
			"ivory_rs4_unmarked",
			"ivory_rs4_unmarked_norb",
			"ivory_rs4_slicktop",
			"ivory_rs4_slicktop_norb",
			"ivory_rs4_slicktop_classic",
			"ivory_suburban_marked",
			"ivory_suburban_marked_norb",
			"ivory_suburban_marked_classic",
			"ivory_suburban_unmarked",
			"ivory_suburban_unmarked_norb",
			"ivory_suburban_slicktop",
			"ivory_suburban_slicktop_norb",
			"ivory_suburban_slicktop_classic",
			"ivory_suburban_ems",
			"ivory_suburban_ems_slicktop",
			"ivory_taurus_marked",
			"ivory_taurus_marked_norb",
			"ivory_taurus_marked_classic",
			"ivory_taurus_unmarked",
			"ivory_taurus_unmarked_norb",
			"ivory_taurus_slicktop",
			"ivory_taurus_slicktop_norb",
			"ivory_taurus_slicktop_classic",
			"ivory_wrx_marked",
			"ivory_wrx_marked_norb",
			"ivory_wrx_marked_classic",
			"ivory_wrx_unmarked",
			"ivory_wrx_unmarked_norb",
			"ivory_wrx_slicktop",
			"ivory_wrx_slicktop_norb",
			"ivory_wrx_slicktop_classic",
			"ivory_911",
			"ivory_c",
			"ivory_ccx",
			"ivory_f1",
			"ivory_lfa",
			"ivory_lp560",
			"ivory_mp4",
			"ivory_r34",
			"ivory_r8",
			"ivory_r8_spyder",
			"ivory_rev",
			"ivory_supra",
			"ivory_supra_topsecret",
			"ivory_veyron",
			"ivory_c_president",
			"ivory_cv_unmarked_taxi",
			"ivory_cv_taxi",
			"ivory_190e",
			"ivory_190e_taxi",
			"ivory_challenger",
			"ivory_charger",
			"ivory_cv",
			"ivory_e36",
			"ivory_elise",
			"ivory_evox",
			"ivory_gt500",
			"ivory_gti",
			"ivory_isf",
			"ivory_m3",
			"ivory_prius",
			"ivory_rs4",
			"ivory_rs4_taxi",
			"ivory_suburban",
			"ivory_taurus",
			"ivory_wrx"
            
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
            //Unarmed
            "CUP_C_Datsun",
			"ivory_challenger_marked",
			"ivory_challenger_marked_norb",
			"ivory_challenger_marked_classic",
			"ivory_challenger_unmarked",
			"ivory_challenger_unmarked_norb",
			"ivory_challenger_slicktop",
			"ivory_challenger_slicktop_norb",
			"ivory_challenger_slicktop_classic",
			"ivory_charger_marked",
			"ivory_charger_marked_norb",
			"ivory_charger_marked_classic",
			"ivory_charger_unmarked",
			"ivory_charger_unmarked_norb",
			"ivory_charger_slicktop",
			"ivory_charger_slicktop_norb",
			"ivory_charger_slicktop_classic",
			"ivory_cv_marked",
			"ivory_cv_marked_norb",
			"ivory_cv_marked_classic",
			"ivory_cv_unmarked",
			"ivory_cv_unmarked_norb",
			"ivory_cv_slicktop",
			"ivory_cv_slicktop_norb",
			"ivory_cv_slicktop_classic",
			"ivory_evox_marked",
			"ivory_evox_marked_norb",
			"ivory_evox_marked_classic",
			"ivory_evox_unmarked",
			"ivory_evox_unmarked_norb",
			"ivory_evox_slicktop",
			"ivory_evox_slicktop_norb",
			"ivory_evox_slicktop_classic",
			"ivory_isf_marked",
			"ivory_isf_marked_norb",
			"ivory_isf_marked_classic",
			"ivory_isf_unmarked",
			"ivory_isf_unmarked_norb",
			"ivory_isf_slicktop",
			"ivory_isf_slicktop_norb",
			"ivory_isf_slicktop_classic",
			"ivory_m3_marked",
			"ivory_m3_marked_norb",
			"ivory_m3_marked_classic",
			"ivory_m3_unmarked",
			"ivory_m3_unmarked_norb",
			"ivory_m3_slicktop",
			"ivory_m3_slicktop_norb",
			"ivory_m3_slicktop_classic",
			"ivory_prius_marked",
			"ivory_prius_marked_norb",
			"ivory_prius_marked_classic",
			"ivory_prius_unmarked",
			"ivory_prius_unmarked_norb",
			"ivory_prius_slicktop",
			"ivory_prius_slicktop_norb",
			"ivory_prius_slicktop_classic",
			"ivory_rev_marked",
			"ivory_rev_marked_norb",
			"ivory_rev_marked_classic",
			"ivory_rev_unmarked",
			"ivory_rev_unmarked_norb",
			"ivory_rev_slicktop",
			"ivory_rev_slicktop_norb",
			"ivory_rev_slicktop_classic",
			"ivory_rs4_marked",
			"ivory_rs4_marked_norb",
			"ivory_rs4_marked_classic",
			"ivory_rs4_unmarked",
			"ivory_rs4_unmarked_norb",
			"ivory_rs4_slicktop",
			"ivory_rs4_slicktop_norb",
			"ivory_rs4_slicktop_classic",
			"ivory_suburban_marked",
			"ivory_suburban_marked_norb",
			"ivory_suburban_marked_classic",
			"ivory_suburban_unmarked",
			"ivory_suburban_unmarked_norb",
			"ivory_suburban_slicktop",
			"ivory_suburban_slicktop_norb",
			"ivory_suburban_slicktop_classic",
			"ivory_suburban_ems",
			"ivory_suburban_ems_slicktop",
			"ivory_taurus_marked",
			"ivory_taurus_marked_norb",
			"ivory_taurus_marked_classic",
			"ivory_taurus_unmarked",
			"ivory_taurus_unmarked_norb",
			"ivory_taurus_slicktop",
			"ivory_taurus_slicktop_norb",
			"ivory_taurus_slicktop_classic",
			"ivory_wrx_marked",
			"ivory_wrx_marked_norb",
			"ivory_wrx_marked_classic",
			"ivory_wrx_unmarked",
			"ivory_wrx_unmarked_norb",
			"ivory_wrx_slicktop",
			"ivory_wrx_slicktop_norb",
			"ivory_wrx_slicktop_classic",
			"ivory_911",
			"ivory_c",
			"ivory_ccx",
			"ivory_f1",
			"ivory_lfa",
			"ivory_lp560",
			"ivory_mp4",
			"ivory_r34",
			"ivory_r8",
			"ivory_r8_spyder",
			"ivory_rev",
			"ivory_supra",
			"ivory_supra_topsecret",
			"ivory_veyron",
			"ivory_c_president",
			"ivory_cv_unmarked_taxi",
			"ivory_cv_taxi",
			"ivory_190e",
			"ivory_190e_taxi",
			"ivory_challenger",
			"ivory_charger",
			"ivory_cv",
			"ivory_e36",
			"ivory_elise",
			"ivory_evox",
			"ivory_gt500",
			"ivory_gti",
			"ivory_isf",
			"ivory_m3",
			"ivory_prius",
			"ivory_rs4",
			"ivory_rs4_taxi",
			"ivory_suburban",
			"ivory_taurus",
			"ivory_wrx"
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
    
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
            "Lada_Civ_04",
			"CUP_C_Datsun",
			"ivory_challenger_marked",
			"ivory_challenger_marked_norb",
			"ivory_challenger_marked_classic",
			"ivory_challenger_unmarked",
			"ivory_challenger_unmarked_norb",
			"ivory_challenger_slicktop",
			"ivory_challenger_slicktop_norb",
			"ivory_challenger_slicktop_classic",
			"ivory_charger_marked",
			"ivory_charger_marked_norb",
			"ivory_charger_marked_classic",
			"ivory_charger_unmarked",
			"ivory_charger_unmarked_norb",
			"ivory_charger_slicktop",
			"ivory_charger_slicktop_norb",
			"ivory_charger_slicktop_classic",
			"ivory_cv_marked",
			"ivory_cv_marked_norb",
			"ivory_cv_marked_classic",
			"ivory_cv_unmarked",
			"ivory_cv_unmarked_norb",
			"ivory_cv_slicktop",
			"ivory_cv_slicktop_norb",
			"ivory_cv_slicktop_classic",
			"ivory_evox_marked",
			"ivory_evox_marked_norb",
			"ivory_evox_marked_classic",
			"ivory_evox_unmarked",
			"ivory_evox_unmarked_norb",
			"ivory_evox_slicktop",
			"ivory_evox_slicktop_norb",
			"ivory_evox_slicktop_classic",
			"ivory_isf_marked",
			"ivory_isf_marked_norb",
			"ivory_isf_marked_classic",
			"ivory_isf_unmarked",
			"ivory_isf_unmarked_norb",
			"ivory_isf_slicktop",
			"ivory_isf_slicktop_norb",
			"ivory_isf_slicktop_classic",
			"ivory_m3_marked",
			"ivory_m3_marked_norb",
			"ivory_m3_marked_classic",
			"ivory_m3_unmarked",
			"ivory_m3_unmarked_norb",
			"ivory_m3_slicktop",
			"ivory_m3_slicktop_norb",
			"ivory_m3_slicktop_classic",
			"ivory_prius_marked",
			"ivory_prius_marked_norb",
			"ivory_prius_marked_classic",
			"ivory_prius_unmarked",
			"ivory_prius_unmarked_norb",
			"ivory_prius_slicktop",
			"ivory_prius_slicktop_norb",
			"ivory_prius_slicktop_classic",
			"ivory_rev_marked",
			"ivory_rev_marked_norb",
			"ivory_rev_marked_classic",
			"ivory_rev_unmarked",
			"ivory_rev_unmarked_norb",
			"ivory_rev_slicktop",
			"ivory_rev_slicktop_norb",
			"ivory_rev_slicktop_classic",
			"ivory_rs4_marked",
			"ivory_rs4_marked_norb",
			"ivory_rs4_marked_classic",
			"ivory_rs4_unmarked",
			"ivory_rs4_unmarked_norb",
			"ivory_rs4_slicktop",
			"ivory_rs4_slicktop_norb",
			"ivory_rs4_slicktop_classic",
			"ivory_suburban_marked",
			"ivory_suburban_marked_norb",
			"ivory_suburban_marked_classic",
			"ivory_suburban_unmarked",
			"ivory_suburban_unmarked_norb",
			"ivory_suburban_slicktop",
			"ivory_suburban_slicktop_norb",
			"ivory_suburban_slicktop_classic",
			"ivory_suburban_ems",
			"ivory_suburban_ems_slicktop",
			"ivory_taurus_marked",
			"ivory_taurus_marked_norb",
			"ivory_taurus_marked_classic",
			"ivory_taurus_unmarked",
			"ivory_taurus_unmarked_norb",
			"ivory_taurus_slicktop",
			"ivory_taurus_slicktop_norb",
			"ivory_taurus_slicktop_classic",
			"ivory_wrx_marked",
			"ivory_wrx_marked_norb",
			"ivory_wrx_marked_classic",
			"ivory_wrx_unmarked",
			"ivory_wrx_unmarked_norb",
			"ivory_wrx_slicktop",
			"ivory_wrx_slicktop_norb",
			"ivory_wrx_slicktop_classic",
			"ivory_911",
			"ivory_c",
			"ivory_ccx",
			"ivory_f1",
			"ivory_lfa",
			"ivory_lp560",
			"ivory_mp4",
			"ivory_r34",
			"ivory_r8",
			"ivory_r8_spyder",
			"ivory_rev",
			"ivory_supra",
			"ivory_supra_topsecret",
			"ivory_veyron",
			"ivory_c_president",
			"ivory_cv_unmarked_taxi",
			"ivory_cv_taxi",
			"ivory_190e",
			"ivory_190e_taxi",
			"ivory_challenger",
			"ivory_charger",
			"ivory_cv",
			"ivory_e36",
			"ivory_elise",
			"ivory_evox",
			"ivory_gt500",
			"ivory_gti",
			"ivory_isf",
			"ivory_m3",
			"ivory_prius",
			"ivory_rs4",
			"ivory_rs4_taxi",
			"ivory_suburban",
			"ivory_taurus",
			"ivory_wrx"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
            //Unarmed
			["Lada_Civ_04", 25],
            ["CUP_C_Datsun", 25],
            ["CUP_C_Datsun_4seat", 25],
            ["CUP_C_Datsun_Plain", 25],
            ["CUP_C_Datsun_Covered", 25],
            ["CUP_C_Datsun_Tubeframe", 25],
            ["CUP_C_Ural_Civ_01", 50],
            ["CUP_C_Ural_Civ_02", 50],
            ["CUP_C_Ural_Civ_03", 50],
            ["CUP_C_Ural_Open_Civ_01", 50],
            ["CUP_C_Ural_Open_Civ_02", 50],
            ["CUP_C_Ural_Open_Civ_03", 50],
            ["CUP_O_Ural_TKA", 50],
            ["CUP_O_Ural_RU", 50],
            ["CUP_I_Ural_UN", 50],
            ["CUP_B_Ural_CDF", 50],
            ["CUP_O_Ural_CHDKZ", 50],
            ["CUP_O_Ural_SLA", 50],
            ["CUP_O_Ural_Open_TKA", 50],
            ["CUP_B_Ural_Open_CDF", 50],
            ["CUP_O_Ural_Open_RU", 50],
            ["CUP_O_Ural_Open_CHDKZ", 50],
            ["CUP_O_Ural_Open_SLA", 50],
            ["CUP_O_Ural_Empty_SLA", 50],
            ["CUP_B_Ural_Empty_CDF", 50],
            ["CUP_I_Ural_Empty_UN", 50],
            ["CUP_O_Ural_Empty_RU", 50],
            ["CUP_O_Ural_Empty_CHDKZ", 50],
            ["CUP_O_Ural_Empty_TKA", 50],
            ["CUP_O_Ural_Repair_SLA", 50],
            ["CUP_O_Ural_Repair_TKA", 50],
            ["CUP_O_Ural_Repair_CHDKZ", 50],
            ["CUP_O_Ural_Repair_RU", 50],
            ["CUP_I_Ural_Repair_UN", 50],
            ["CUP_B_Ural_Repair_CDF", 50],
            ["CUP_B_Ural_Refuel_CDF", 50],
            ["CUP_O_Ural_Refuel_RU", 50],
            ["CUP_O_Ural_Refuel_CHDKZ", 50],
            ["CUP_O_Ural_Refuel_TKA", 50],
            ["CUP_O_Ural_Refuel_SLA", 50],
            ["CUP_C_LR_Transport_CTK", 150],
            ["CUP_O_LR_Transport_TKA", 150],
            ["CUP_O_LR_Transport_TKM", 150],
            ["CUP_B_LR_Transport_CZ_W", 150],
            ["CUP_B_LR_Transport_CZ_D", 150],
            ["CUP_B_LR_Transport_GB_W", 150],
            ["CUP_B_LR_Transport_GB_D", 150],
            ["CUP_B_LR_Ambulance_CZ_W", 25],
            ["CUP_B_LR_Ambulance_CZ_D", 25],
            ["CUP_B_LR_Ambulance_GB_W", 25],
            ["CUP_B_LR_Ambulance_GB_D", 25],
            ["CUP_O_LR_Ambulance_TKA", 25],
            ["CUP_C_UAZ_Unarmed_TK_CIV", 25],
            ["CUP_O_UAZ_Unarmed_RU", 25],
            ["CUP_I_UAZ_Unarmed_UN", 25],
            ["CUP_O_UAZ_Unarmed_TKA", 25],
            ["CUP_O_UAZ_Unarmed_CHDKZ", 25],
            ["CUP_B_UAZ_Unarmed_ACR", 25],
            ["CUP_B_UAZ_Unarmed_CDF", 25],
            ["CUP_C_UAZ_Open_TK_CIV", 25],
            ["CUP_O_UAZ_Open_CHDKZ", 25],
            ["CUP_O_UAZ_Open_RU", 25],
            ["CUP_O_UAZ_Open_TKA", 25],
            ["CUP_I_UAZ_Open_UN", 25],
            ["CUP_B_UAZ_Open_ACR", 25],
            ["CUP_B_UAZ_Open_CDF", 25],
            ["CUP_B_HMMWV_Unarmed_USA", 25],
            ["CUP_B_HMMWV_Unarmed_USMC", 25],
            ["CUP_B_HMMWV_Ambulance_USMC", 25],
            ["CUP_B_HMMWV_Ambulance_USA", 25],
            ["CUP_B_HMMWV_Ambulance_ACR", 25],
            ["CUP_B_HMMWV_Transport_USA", 50],
            ["CUP_I_M113_Med_RACS", 25],
            ["CUP_I_M113_Med_UN", 25],
			//fox
			["Fox_BUS", 75],
			["Fox_MEGABUS", 75],
			["Fox_Fireengine", 75],
			["Fox_Truck", 50],
			["Fox_ChallengerO", 25],
			["Fox_ChallengerW", 25],
			["Fox_ChallengerDev1", 25],
			["Fox_ChallengerDev2", 25],
			["Fox_ChallengerYB", 25],
			["Fox_ChallengerBR", 25],
			["Fox_Daytona", 25],
			["Fox_DaytonaGeneral", 25],
			["Fox_DaytonaStratos", 25],
			["Fox_Interceptor", 25],
			["Fox_Landrover", 25],
			["Fox_Landrover2", 25],
			["Fox_CobraR_Police", 25],
			["Fox_LandCruiserPolice", 25],
			["Fox_LandCruiser", 25],
			["Fox_LandCruiser2", 25],
			["Fox_LandCruiser3", 25],
			["Fox_M5TG", 25],
			["Fox_Outsider", 25],
			["Fox_GNX", 25],
			["Fox_Viper", 25],
			["Fox_F40", 25],
			["Fox_Tahoe_Apocalypse", 25],
			["Fox_Charger_Apocalypse", 25],
			["Fox_Pickup_Apocalypse", 25],
			["Fox_Pickup_Tow", 25],
			["Fox_Pickup_6S", 25],
			["Fox_Patrol", 25],
			["Fox_Patrol2", 25],
			["Fox_Patrol3", 25],
			["Fox_R34_Fox", 25],
			["Fox_R34_Apocalypse", 25],
			["Fox_Wanderer", 25],
			["Fox_RickGrimes", 25],
			["Fox_Tahoe", 25],
            
            //Armed
			["Wheeled_APC_F",50],
			["CUP_StrykerBase", 50],
            ["CUP_O_LR_MG_TKM", 25],
            ["CUP_O_LR_MG_TKA", 25],
            ["CUP_I_Datsun_PK", 25],
            ["CUP_I_Datsun_PK_Random", 25],
            ["CUP_I_Datsun_PK_TK", 25],
            ["CUP_I_Datsun_PK_TK_Random", 25],
            ["CUP_O_Datsun_PK", 25],
            ["CUP_O_Datsun_PK_Random", 25],
            ["CUP_O_UAZ_MG_CHDKZ", 25],
            ["CUP_O_UAZ_MG_RU", 25],
            ["CUP_O_UAZ_MG_TKA", 25],
            ["CUP_I_UAZ_MG_UN", 25],
            ["CUP_B_UAZ_MG_ACR", 25],
            ["CUP_B_UAZ_MG_CDF", 25],
            ["CUP_B_UAZ_AGS30_CDF", 25],
            ["CUP_O_UAZ_AGS30_CHDKZ", 25],
            ["CUP_O_UAZ_AGS30_RU", 25],
            ["CUP_O_UAZ_AGS30_TKA", 25],
            ["CUP_I_UAZ_AGS30_UN", 25],
            ["CUP_I_M113_RACS", 25],
            ["CUP_I_M113_UN", 25],
            ["CUP_BAF_Jackal2_L2A1_W", 25],
            ["CUP_BAF_Jackal2_L2A1_D", 25],
            ["CUP_BAF_Jackal2_GMG_D", 25],
            ["CUP_BAF_Jackal2_GMG_W", 25],
            ["CUP_B_LR_Special_CZ_W", 25],
            ["CUP_B_LR_Special_Des_CZ_D", 25],
            ["CUP_B_LR_MG_CZ_W", 25],
            ["CUP_B_LR_MG_GB_W", 25],
            ["CUP_B_HMMWV_M1114_USMC", 25],
            ["CUP_B_HMMWV_M2_USMC", 25],
            ["CUP_B_HMMWV_Crows_M2_USA", 25],
            ["CUP_B_HMMWV_M2_GPK_USA", 25],
            ["CUP_B_HMMWV_M2_USA", 25],
            ["CUP_B_HMMWV_DSHKM_GPK_ACR", 25],
            ["CUP_B_HMMWV_AGS_GPK_ACR", 25],
            ["CUP_B_HMMWV_MK19_USMC", 25],
            ["CUP_B_HMMWV_MK19_USA", 25],
            ["CUP_B_HMMWV_Crows_MK19_USA", 25],
            ["CUP_B_HMMWV_SOV_USA", 25],
            ["CUP_B_BRDM2_HQ_CDF", 25],
            ["CUP_O_BRDM2_HQ_SLA", 25],
            ["CUP_I_BRDM2_HQ_UN", 25],
            ["CUP_I_BRDM2_HQ_NAPA", 25],
            ["CUP_I_BRDM2_HQ_TK_Gue", 25],
            ["CUP_O_BRDM2_HQ_TKA", 25],
            ["CUP_O_BRDM2_HQ_CHDKZ", 25],
            ["CUP_O_BRDM2_CHDKZ", 25],
            ["CUP_O_BRDM2_SLA", 25],
            ["CUP_O_BRDM2_TKA", 25],
            ["CUP_I_BRDM2_NAPA", 25],
            ["CUP_I_BRDM2_TK_Gue", 25],
            ["CUP_I_BRDM2_UN", 25],
            ["CUP_B_BRDM2_CDF", 25],
			//ivory
			["ivory_challenger_marked", 50],
			["ivory_challenger_marked_norb", 50],
			["ivory_challenger_marked_classic", 50],
			["ivory_challenger_unmarked", 50],
			["ivory_challenger_unmarked_norb", 50],
			["ivory_challenger_slicktop", 50],
			["ivory_challenger_slicktop_norb", 50],
			["ivory_challenger_slicktop_classic", 50],
			["ivory_charger_marked", 50],
			["ivory_charger_marked_norb", 50],
			["ivory_charger_marked_classic", 50],
			["ivory_charger_unmarked", 50],
			["ivory_charger_unmarked_norb", 50],
			["ivory_charger_slicktop", 50],
			["ivory_charger_slicktop_norb", 50],
			["ivory_charger_slicktop_classic", 50],
			["ivory_cv_marked", 50],
			["ivory_cv_marked_norb", 50],
			["ivory_cv_marked_classic", 50],
			["ivory_cv_unmarked", 50],
			["ivory_cv_unmarked_norb", 50],
			["ivory_cv_slicktop", 50],
			["ivory_cv_slicktop_norb", 50],
			["ivory_cv_slicktop_classic", 50],
			["ivory_evox_marked", 50],
			["ivory_evox_marked_norb", 50],
			["ivory_evox_marked_classic", 50],
			["ivory_evox_unmarked", 50],
			["ivory_evox_unmarked_norb", 50],
			["ivory_evox_slicktop", 50],
			["ivory_evox_slicktop_norb", 50],
			["ivory_evox_slicktop_classic", 50],
			["ivory_isf_marked", 50],
			["ivory_isf_marked_norb", 50],
			["ivory_isf_marked_classic", 50],
			["ivory_isf_unmarked", 50],
			["ivory_isf_unmarked_norb", 50],
			["ivory_isf_slicktop", 50],
			["ivory_isf_slicktop_norb", 50],
			["ivory_isf_slicktop_classic", 50],
			["ivory_m3_marked", 50],
			["ivory_m3_marked_norb", 50],
			["ivory_m3_marked_classic", 50],
			["ivory_m3_unmarked", 50],
			["ivory_m3_unmarked_norb", 50],
			["ivory_m3_slicktop", 50],
			["ivory_m3_slicktop_norb", 50],
			["ivory_m3_slicktop_classic", 50],
			["ivory_prius_marked", 50],
			["ivory_prius_marked_norb", 50],
			["ivory_prius_marked_classic", 50],
			["ivory_prius_unmarked", 50],
			["ivory_prius_unmarked_norb", 50],
			["ivory_prius_slicktop", 50],
			["ivory_prius_slicktop_norb", 50],
			["ivory_prius_slicktop_classic", 50],
			["ivory_rev_marked", 50],
			["ivory_rev_marked_norb", 50],
			["ivory_rev_marked_classic", 50],
			["ivory_rev_unmarked", 50],
			["ivory_rev_unmarked_norb", 50],
			["ivory_rev_slicktop", 50],
			["ivory_rev_slicktop_norb", 50],
			["ivory_rev_slicktop_classic", 50],
			["ivory_rs4_marked", 50],
			["ivory_rs4_marked_norb", 50],
			["ivory_rs4_marked_classic", 50],
			["ivory_rs4_unmarked", 50],
			["ivory_rs4_unmarked_norb", 50],
			["ivory_rs4_slicktop", 50],
			["ivory_rs4_slicktop_norb", 50],
			["ivory_rs4_slicktop_classic", 50],
			["ivory_suburban_marked", 50],
			["ivory_suburban_marked_norb", 50],
			["ivory_suburban_marked_classic", 50],
			["ivory_suburban_unmarked", 50],
			["ivory_suburban_unmarked_norb", 50],
			["ivory_suburban_slicktop", 50],
			["ivory_suburban_slicktop_norb", 50],
			["ivory_suburban_slicktop_classic", 50],
			["ivory_suburban_ems", 50],
			["ivory_suburban_ems_slicktop", 50],
			["ivory_taurus_marked", 50],
			["ivory_taurus_marked_norb", 50],
			["ivory_taurus_marked_classic", 50],
			["ivory_taurus_unmarked", 50],
			["ivory_taurus_unmarked_norb", 50],
			["ivory_taurus_slicktop", 50],
			["ivory_taurus_slicktop_norb", 50],
			["ivory_taurus_slicktop_classic", 50],
			["ivory_wrx_marked", 50],
			["ivory_wrx_marked_norb", 50],
			["ivory_wrx_marked_classic", 50],
			["ivory_wrx_unmarked", 50],
			["ivory_wrx_unmarked_norb", 50],
			["ivory_wrx_slicktop", 50],
			["ivory_wrx_slicktop_norb", 50],
			["ivory_wrx_slicktop_classic", 50],
			["ivory_911", 50],
			["ivory_c", 50],
			["ivory_ccx", 50],
			["ivory_f1", 50],
			["ivory_lfa", 50],
			["ivory_lp560", 50],
			["ivory_mp4", 50],
			["ivory_r34", 50],
			["ivory_r8", 50],
			["ivory_r8_spyder", 50],
			["ivory_rev", 50],
			["ivory_supra", 50],
			["ivory_supra_topsecret", 50],
			["ivory_veyron", 50],
			["ivory_c_president", 50],
			["ivory_cv_unmarked_taxi", 50],
			["ivory_cv_taxi", 50],
			["ivory_190e", 50],
			["ivory_190e_taxi", 50],
			["ivory_challenger", 50],
			["ivory_charger", 50],
			["ivory_cv", 50],
			["ivory_e36", 50],
			["ivory_elise", 50],
			["ivory_evox", 50],
			["ivory_gt500", 50],
			["ivory_gti", 50],
			["ivory_isf", 50],
			["ivory_m3", 50],
			["ivory_prius", 50],
			["ivory_rs4", 50],
			["ivory_rs4_taxi", 50],
			["ivory_suburban", 50],
			["ivory_taurus", 50],
			["ivory_wrx", 50]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
		["CUP_I_Igla_AA_pod_AAF", 25],
		["RHS_Stinger_AA_pod_D", 25],
		["CUP_I_RBS70_AA_pod_AAF", 25],
		["CUP_I_TOW_TriPod_AAF", 25],
		["CUP_I_ZU23_AAF", 25],
		["CUP_I_DSHKM_AAF", 25],
		["CUP_I_DSHKM_MiniTriPod_AAF", 25],
		["CUP_I_KORD_AAF", 25],
		["CUP_I_KORD_high_AAF", 25],
		["CUP_I_M2StaticMG_AAF", 25],
		["CUP_I_M2StaticMG_MiniTripod_AAF", 25],
		["CUP_I_MK19_TriPod_AAF", 25],
		["B_T_GMG_01_F", 25],
		["B_T_HMG_01_F", 25],
		["CUP_I_Metis_AAF", 25],
		["CUP_I_SPG9_AAF", 25],
		["B_T_Static_AA_F", 25],
		["B_T_Static_AT_F", 25]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
		"CUP_I_Igla_AA_pod_AAF",
		"RHS_Stinger_AA_pod_D",
		"CUP_I_RBS70_AA_pod_AAF",
		"CUP_I_TOW_TriPod_AAF",
		"CUP_I_ZU23_AAF",
		"CUP_I_DSHKM_AAF",
		"CUP_I_DSHKM_MiniTriPod_AAF",
		"CUP_I_KORD_AAF",
		"CUP_I_KORD_high_AAF",
		"CUP_I_M2StaticMG_AAF",
		"CUP_I_M2StaticMG_MiniTripod_AAF",
		"CUP_I_MK19_TriPod_AAF",
		"B_T_GMG_01_F",
		"B_T_HMG_01_F",
		"CUP_I_Metis_AAF",
		"CUP_I_SPG9_AAF",
		"B_T_Static_AA_F",
		"B_T_Static_AT_F"
];