	///////// Weapons /////////
	////////////////////////////////////////////////////////////////////
	//  Weapons - Pistols
	////////////////////////////////////////////////////////////////////
	class Pistols 
	{
		name = "Pistols";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
		items[] = 
		{
			"hgun_ACPC2_F",
			"hgun_P07_F",
			"hgun_Pistol_heavy_01_F",
			"hgun_Pistol_heavy_02_F",
			"hgun_Pistol_Signal_F",
			"hgun_Rook40_F",
			//"Exile_Weapon_Colt1911",
			//"Exile_Weapon_Makarov",
			//"Exile_Weapon_Taurus",
			//"Exile_Weapon_TaurusGold",
			//Apex
			"hgun_Pistol_01_F",
			"hgun_P07_khk_F",
			"CUP_hgun_Compact",
			"CUP_hgun_Duty",
			"CUP_hgun_Phantom",
			"CUP_hgun_Glock17",
			"CUP_hgun_Glock17_blk",
			"CUP_hgun_M9",
			"CUP_hgun_BallisticShield_Armed",
			"CUP_hgun_Makarov",
			"CUP_hgun_Mac10",
			"CUP_hgun_PMM",
			"CUP_hgun_MicroUzi",
			"CUP_hgun_Mk23",
			"CUP_hgun_PB6P9",
			"CUP_hgun_TaurusTracker455",
			"CUP_hgun_TaurusTracker455_gold",
			"CUP_hgun_TEC9",
			"CUP_hgun_Colt1911",
			"CUP_hgun_Deagle",
			"CUP_hgun_MP7",
			"CUP_hgun_MP7_woodland",
			"CUP_hgun_SA61"
		};
	};
	////////////////////////////////////////////////////////////////////
	//  Weapons - Sub Machine Guns
	////////////////////////////////////////////////////////////////////
	class SubMachineGuns 
	{
		name = "Sub Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"hgun_PDW2000_F",
			"SMG_01_F",
			"SMG_02_F",
			"SMG_05_F",
			//"CUP_smg_Mac10",
			"CUP_smg_Mac10_rail",
			"CUP_smg_MP5SD6",
			"CUP_smg_MP5A5",
			//"CUP_smg_MP5A5_flashlight",
			"CUP_smg_p90_olive",
			"CUP_smg_p90_black",
			"CUP_smg_PS90_olive",
			"CUP_smg_bizon",
			//"CUP_smg_vityaz",
			//"CUP_smg_vityaz_vfg",
			"CUP_smg_vityaz_top_rail",
			"CUP_smg_vityaz_vfg_top_rail",
			"CUP_smg_vityaz_vfg_front_rail",
			"CUP_smg_saiga9",
			"CUP_smg_EVO",
			"CUP_smg_MP7",
			"CUP_smg_MP7_woodland",
			"CUP_smg_SA61"
		};
	};
	////////////////////////////////////////////////////////////////////
	//  Weapons - Light Machine Guns
	////////////////////////////////////////////////////////////////////
	class LightMachineGuns 
	{
		name = "Light Machine Guns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"arifle_MX_SW_Black_F",
			///"arifle_MX_SW_F",
			"LMG_Mk200_F",
			"LMG_Zafir_F",
			"LMG_03_F",
			//"Exile_Weapon_RPK",
			//"Exile_Weapon_PK",
			//"Exile_Weapon_PKP",
			"CUP_lmg_UK59",
			"CUP_lmg_M240",
			"CUP_lmg_L7A2",
			"CUP_lmg_L7A2_Flat",
			"CUP_lmg_FNMAG",
			"CUP_lmg_FNMAG_RIS",
			"CUP_lmg_minimipara",
			//"CUP_lmg_minimi",
			"CUP_lmg_minimi_railed",
			"CUP_lmg_m249_para",
			"CUP_lmg_m249_para_gl",
			"CUP_lmg_M249_E2",
			"CUP_lmg_m249_pip1",
			"CUP_lmg_M249",
			"CUP_lmg_m249_pip2",
			"CUP_lmg_m249_pip3",
			"CUP_lmg_m249_pip4",
			"CUP_lmg_m249_SQuantoon",
			"CUP_lmg_L110A1",
			"CUP_lmg_M60E4",
			//"CUP_lmg_M60E4_norail",
			"CUP_lmg_M60E4_wood",
			//"CUP_lmg_M60E4_norail_wood",
			"CUP_lmg_M60E4_jungle",
			//"CUP_lmg_M60E4_norail_jungle",
			"CUP_lmg_M60",
			//"CUP_lmg_MG3",
			"CUP_lmg_MG3_rail",
			"CUP_lmg_Mk48",
			"CUP_lmg_Mk48_wdl",
			"CUP_lmg_Mk48_od",
			"CUP_lmg_Mk48_nohg",
			"CUP_lmg_Mk48_nohg_wdl",
			"CUP_lmg_Mk48_nohg_od",
			"CUP_lmg_PKM",
			"CUP_lmg_PKMN",
			"CUP_lmg_Pecheneg",
			"CUP_lmg_Pecheneg_woodland"
		};
	};
	////////////////////////////////////////////////////////////////////
	//  Weapons - AsaultRifles
	////////////////////////////////////////////////////////////////////
	class AssaultRifles
	{
		name = "Assault Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			//"arifle_Katiba_C_F",
			//"arifle_Katiba_F",
			//"arifle_Katiba_GL_F",
			"arifle_Mk20_F",
			//"arifle_Mk20_GL_F",
			//"arifle_Mk20_GL_plain_F",
			//"arifle_Mk20_plain_F",
			//"arifle_Mk20C_F",
			//"arifle_Mk20C_plain_F",
			"arifle_MX_Black_F",
			//"arifle_MX_F",
			//"arifle_MX_GL_Black_F",
			//"arifle_MX_GL_F",
			//"arifle_MXC_Black_F",
			//"arifle_MXC_F",
			"arifle_SDAR_F",
			"arifle_TRG20_F",
			//"arifle_TRG21_F",
			//"arifle_TRG21_GL_F",
			//"Exile_Weapon_AK107",
			//"Exile_Weapon_AK107_GL",
			//"Exile_Weapon_AK74",
			//"Exile_Weapon_AK74_GL",
			//"Exile_Weapon_AK47",
			//"Exile_Weapon_AKS_Gold",
			"arifle_AK12_F",
			//"arifle_AK12_GL_F",
			"arifle_AKM_F",
			//"arifle_AKM_FL_F",
			"arifle_AKS_F",
			"arifle_ARX_blk_F",
			//"arifle_ARX_ghex_F",
			//"arifle_ARX_hex_F",
			"arifle_CTAR_blk_F",
			//"arifle_CTAR_hex_F",
			//"arifle_CTAR_ghex_F",
			//"arifle_CTAR_GL_blk_F",
			"arifle_CTARS_blk_F",
			//"arifle_CTARS_hex_F",
			//"arifle_CTARS_ghex_F",
			"arifle_SPAR_01_blk_F",
			//"arifle_SPAR_01_khk_F",
			//"arifle_SPAR_01_snd_F",
			//"arifle_SPAR_01_GL_blk_F",
			//"arifle_SPAR_01_GL_khk_F",
			//"arifle_SPAR_01_GL_snd_F",
			"arifle_SPAR_02_blk_F",
			//"arifle_SPAR_02_khk_F",
			//"arifle_SPAR_02_snd_F",			
			"arifle_SPAR_03_blk_F",
			//"arifle_SPAR_03_khk_F",
			//"arifle_SPAR_03_snd_F",
			//"arifle_MX_khk_F",
			//"arifle_MX_GL_khk_F",
			//"arifle_MXC_khk_F",
			//"arifle_MXM_khk_F",
			"CUP_arifle_G3A3_ris",
			"CUP_arifle_G3A3_ris_vfg",
			"CUP_arifle_G3A3_modern_ris",
			"CUP_arifle_G3A3_ris_black",
			"CUP_arifle_G3A3_ris_vfg_black",
			"CUP_arifle_G3A3_modern_ris_black",
			//"CUP_arifle_ACR_blk_556",
			//"CUP_arifle_ACR_wdl_556",
			//"CUP_arifle_ACRC_blk_556",
			//"CUP_arifle_ACRC_wdl_556",
			//"CUP_arifle_ACR_DMR_blk_556",
			//"CUP_arifle_ACR_DMR_wdl_556",
			//"CUP_arifle_ACR_EGLM_blk_556",
			//"CUP_arifle_ACR_EGLM_wdl_556",
			//"CUP_arifle_ACRC_EGLM_blk_556",
			//"CUP_arifle_ACRC_EGLM_wdl_556",
			//"CUP_arifle_ACR_blk_68",
			//"CUP_arifle_ACR_wdl_68",
			//"CUP_arifle_ACRC_blk_68",
			//"CUP_arifle_ACRC_wdl_68",
			//"CUP_arifle_ACR_DMR_blk_68",
			//"CUP_arifle_ACR_DMR_wdl_68",
			//"CUP_arifle_ACR_EGLM_blk_68",
			//"CUP_arifle_ACR_EGLM_wdl_68",
			//"CUP_arifle_ACRC_EGLM_blk_68",
			//"CUP_arifle_ACRC_EGLM_wdl_68",
			"CUP_CZ_BREN2_556_14",
			"CUP_CZ_BREN2_556_14_GL",
			"CUP_CZ_BREN2_556_11",
			"CUP_CZ_BREN2_556_11_GL",
			"CUP_CZ_BREN2_556_8",
			"CUP_CZ_BREN2_762_14",
			"CUP_CZ_BREN2_762_14_GL",
			"CUP_CZ_BREN2_762_8",
			"CUP_arifle_Galil_black",
			//"CUP_arifle_Galil_556_black",
			//"CUP_arifle_Galil_SAR_black",
			//"CUP_arifle_OTS14_GROZA_GL",
			//"CUP_arifle_OTS14_GROZA_Grip",
			"CUP_arifle_OTS14_GROZA",
			//"CUP_arifle_OTS14_GROZA_762_Grip",
			//"CUP_arifle_OTS14_GROZA_762",
			//"CUP_arifle_OTS14_GROZA_762_GL",
			"CUP_arifle_AUG_A1",
			//"CUP_arifle_AS_VAL",
			"CUP_arifle_AS_VAL_top_rail",
			//"CUP_arifle_AS_VAL_VFG",
			"CUP_arifle_AS_VAL_VFG_top_rail",
			//"CUP_arifle_AS_VAL_flash",
			//"CUP_arifle_SR3M_Vikhr",
			"CUP_arifle_SR3M_Vikhr_top_rail",
			//"CUP_arifle_SR3M_Vikhr_VFG",
			"CUP_arifle_SR3M_Vikhr_VFG_top_rail",
			"CUP_arifle_X95",
			//"CUP_arifle_X95_Grippod",
			"CUP_arifle_Fort224",
			//"CUP_arifle_Fort224_Grippod",
			"CUP_arifle_Fort221",
			"CUP_arifle_Fort222",
			//"CUP_arifle_AKM",
			//"CUP_arifle_AKM_GL",
			"CUP_arifle_AKM_top_rail",
			//"CUP_arifle_AKM_GL_top_rail",
			//"CUP_arifle_AKM_Early",
			//"CUP_arifle_AKM_GL_Early",
			//"CUP_arifle_AKMN_railed",
			//"CUP_arifle_AKMN_railed_afg",
			//"CUP_arifle_AKMS",
			//"CUP_arifle_AKMS_top_rail",
			//"CUP_arifle_AKMS_GL",
			//"CUP_arifle_AKMS_GL_top_rail",
			//"CUP_arifle_AKMS_Early",
			//"CUP_arifle_AKMS_GL_E",
			//"CUP_arifle_AKS74U",
			//"CUP_arifle_AKS74U_top_rail",
			//"CUP_arifle_AKS74U_railed",
			//"CUP_arifle_AKS",
			"CUP_arifle_AKS_Gold",
			"CUP_arifle_AKS_top_rail",
			//"CUP_arifle_AKS74",
			//"CUP_arifle_AKS74_GL",
			//"CUP_arifle_AKS74_top_rail",
			//"CUP_arifle_AKS74_GL_top_rail",
			//"CUP_arifle_AKS74_Early",
			//"CUP_arifle_AKS74_GL_Early",
			//"CUP_arifle_AK47",
			//"CUP_arifle_AK47_GL",
			"CUP_arifle_AK47_top_rail",
			"CUP_arifle_AK47_GL_top_rail",
			//"CUP_arifle_AK47_Early",
			//"CUP_arifle_AK47_GL_Early",
			//"CUP_arifle_AK74",
			//"CUP_arifle_AK74_GL",
			"CUP_arifle_AK74_top_rail",
			"CUP_arifle_AK74_GL_top_rail",
			//"CUP_arifle_AK74_Early",
			//"CUP_arifle_AK74_GL_Early",
			//"CUP_arifle_AK74M",
			//"CUP_arifle_AK74M_GL",
			//"CUP_arifle_AK74M_top_rail",
			//"CUP_arifle_AK74M_GL_top_rail",
			//"CUP_arifle_AK74M_railed",
			//"CUP_arifle_AK74M_GL_railed",
			//"CUP_arifle_AK74M_railed_afg",
			//"CUP_arifle_AK74M_camo",
			//"CUP_arifle_AK74M_top_rail_camo",
			//"CUP_arifle_AK74M_railed_camo",
			//"CUP_arifle_AK74M_GL_camo",
			//"CUP_arifle_AK74M_GL_top_rail_camo",
			//"CUP_arifle_AK74M_GL_railed_camo",
			//"CUP_arifle_AK74M_railed_afg_camo",
			//"CUP_arifle_AK101",
			//"CUP_arifle_AK101_GL",
			//"CUP_arifle_AK101_top_rail",
			//"CUP_arifle_AK101_GL_top_rail",
			//"CUP_arifle_AK101_railed",
			//"CUP_arifle_AK101_GL_railed",
			//"CUP_arifle_AK103",
			//"CUP_arifle_AK103_GL",
			//"CUP_arifle_AK103_top_rail",
			//"CUP_arifle_AK103_GL_top_rail",
			//"CUP_arifle_AK103_railed",
			//"CUP_arifle_AK103_GL_railed",
			//"CUP_arifle_AK107",
			//"CUP_arifle_AK107_GL",
			//"CUP_arifle_AK107_top_rail",
			//"CUP_arifle_AK107_GL_top_rail",
			//"CUP_arifle_AK107_railed",
			//"CUP_arifle_AK107_GL_railed",
			//"CUP_arifle_AK108",
			//"CUP_arifle_AK108_GL",
			//"CUP_arifle_AK108_top_rail",
			//"CUP_arifle_AK108_GL_top_rail",
			//"CUP_arifle_AK108_railed",
			//"CUP_arifle_AK108_GL_railed",
			//"CUP_arifle_AK109",
			//"CUP_arifle_AK109_GL",
			//"CUP_arifle_AK109_top_rail",
			//"CUP_arifle_AK109_GL_top_rail",
			//"CUP_arifle_AK109_railed",
			//"CUP_arifle_AK109_GL_railed",
			//"CUP_arifle_AK102",
			//"CUP_arifle_AK102_top_rail",
			//"CUP_arifle_AK102_railed",
			//"CUP_arifle_AK104",
			//"CUP_arifle_AK104_top_rail",
			//"CUP_arifle_AK104_railed",
			//"CUP_arifle_AK105",
			//"CUP_arifle_AK105_top_rail",
			//"CUP_arifle_AK105_railed",
			//"CUP_arifle_RPK74",
			"CUP_arifle_RPK74_top_rail",
			//"CUP_arifle_RPK74_45",
			"CUP_arifle_RPK74_45_top_rail",
			//"CUP_arifle_RPK74M",
			"CUP_arifle_RPK74M_top_rail",
			"CUP_arifle_RPK74M_railed",
			//"CUP_arifle_SAIGA_MK03",
			"CUP_arifle_SAIGA_MK03_top_rail",
			//"CUP_arifle_SAIGA_MK03_Wood",
			"CUP_arifle_SIAGE_MK03_Wood_top_rail",
			//"CUP_arifle_TYPE_56_2",
			"CUP_arifle_TYPE_56_2_top_rail",
			//"CUP_arifle_TYPE_56_2_Early",
			"CUP_arifle_CZ805_A2",
			"CUP_arifle_CZ805_A1",
			"CUP_arifle_CZ805_GL",
			"CUP_arifle_CZ805_A2_blk",
			"CUP_arifle_CZ805_A1_blk",
			"CUP_arifle_CZ805_GL_blk",
			"CUP_arifle_CZ805_B",
			"CUP_arifle_CZ805_B_GL",
			//"CUP_Famas_F1",
			"CUP_Famas_F1_Rail",
			//"CUP_Famas_F1_Wood",
			"CUP_Famas_F1_Rail_Wood",
			//"CUP_arifle_FNFAL",
			"CUP_arifle_FNFAL_railed",
			//"CUP_arifle_FNFAL_woodland",
			"CUP_arifle_FNFAL_railed_woodland",
			//"CUP_arifle_FNFAL5060",
			"CUP_arifle_FNFAL5060_railed",
			//"CUP_arifle_FNFAL5060_rhodesian",
			//"CUP_arifle_FNFAL5060_woodland",
			"CUP_arifle_FNFAL5060_railed_woodland",
			//"CUP_arifle_FNFAL5061",
			"CUP_arifle_FNFAL5061_railed",
			//"CUP_arifle_FNFAL5061_rhodesian",
			//"CUP_arifle_FNFAL5061_wooden",
			"CUP_arifle_FNFAL5061_wooden_railed",
			//"CUP_arifle_FNFAL5062",
			"CUP_arifle_FNFAL5062_railed",
			//"CUP_arifle_FNFAL_OSW",
			"CUP_arifle_FNFAL_OSW_railed",
			//"CUP_arifle_IMI_Romat",
			"CUP_arifle_IMI_Romat_railed",
			//"CUP_arifle_DSA_SA58",
			//"CUP_arifle_DSA_SA58_OSW",
			//"CUP_arifle_DSA_SA58_OSW_VFG",
			//"CUP_arifle_DSA_SA58_OSW_M203",
			//"CUP_arifle_DSA_SA58_DMR",
			//"CUP_arifle_DSA_SA58_OSW_Woodland",
			//"CUP_arifle_DSA_SA58_OSW_VFG_Woodland",

			//"CUP_arifle_G36A_RIS",
			//"CUP_arifle_G36A_RIS_wdl",
			//"CUP_arifle_G36A_AG36_RIS",
			//"CUP_arifle_G36A_AG36_RIS_wdl",
			//"CUP_arifle_G36K_RIS",
			//"CUP_arifle_G36K_RIS_wdl",
			//"CUP_arifle_G36K_RIS_hex",
			//"CUP_arifle_G36K_RIS_AG36",
			//"CUP_arifle_G36K_RIS_AG36_wdl",
			//"CUP_arifle_G36K_RIS_AG36_hex",
			//"CUP_arifle_G36K_KSK",
			//"CUP_arifle_G36K_KSK_hex",
			//"CUP_arifle_G36K_KSK_VFG",
			//"CUP_arifle_G36K_KSK_VFG_hex",
			//"CUP_arifle_G36C",
			//"CUP_arifle_G36C_wdl",
			//"CUP_arifle_G36C_hex",
			//"CUP_arifle_G36C_VFG",
			//"CUP_arifle_G36C_VFG_wdl",
			//"CUP_arifle_G36C_VFG_hex",
			//"CUP_arifle_MG36",
			//"CUP_arifle_MG36_wdl",
			//"CUP_arifle_MG36_hex",
			//HK
			"CUP_arifle_HK416_CQB_Black",
			"CUP_arifle_HK416_CQB_Wood",
			//"CUP_arifle_HK416_Black",
			//"CUP_arifle_HK416_Wood",
			//"CUP_arifle_HK416_M203_Black",
			//"CUP_arifle_HK416_M203_Wood",
			"CUP_arifle_HK416_CQB_M203_Black",
			"CUP_arifle_HK416_CQB_M203_Wood",
			//"CUP_arifle_HK416_AGL_Black",
			//"CUP_arifle_HK416_AGL_Wood",
			"CUP_arifle_HK416_CQB_AG36",
			//"CUP_arifle_HK416_CQB_AG36_Desert",
			"CUP_arifle_HK416_CQB_AG36_Wood",

			"CUP_arifle_HK417_20",
			"CUP_arifle_HK417_20_Wood",
			"CUP_arifle_HK417_12",
			"CUP_arifle_HK417_12_Wood",
			"CUP_arifle_HK417_12_M203",
			"CUP_arifle_HK417_12_M203_Wood",
			"CUP_arifle_HK417_12_AG36",
			"CUP_arifle_HK417_12_AG36_Wood",
			//L85
			//"CUP_l85a2",
			//"CUP_l85a2_ris",
			//"CUP_l85a2_ris_ng",
			//"CUP_l85a2_ugl",
			"CUP_arifle_L85A2",
			"CUP_arifle_L85A2_G",
			"CUP_arifle_L85A2_NG",
			"CUP_arifle_L85A2_GL",
			"CUP_arifle_L86A2",
			//m16
			"CUP_arifle_M16A2",
			"CUP_arifle_M16A2_GL",
			"CUP_arifle_M16A4_Grip",
			"CUP_arifle_M16A4_GL",
			//"CUP_arifle_XM16E1",
			//"CUP_arifle_M16A1",
			//"CUP_arifle_M16A1GL",
			//"CUP_arifle_M16A1GL_USA",
			//"CUP_arifle_M16A1GL_FS",
			//colt
			"CUP_arifle_Colt727",
			"CUP_arifle_Colt727_M203",
			//m4
			//"CUP_arifle_M4A1",
			//"CUP_arifle_M4A1_camo_carryhandle",
			//"CUP_arifle_M4A1_GL_carryhandle",
			//"CUP_arifle_M4A1_GL_carryhandle_camo",
			//"CUP_arifle_M4A1_black",
			//"CUP_arifle_M4A1_camo",
			//"CUP_arifle_M4A1_BUIS_GL",
			//"CUP_arifle_M4A1_BUIS_camo_GL",
			"CUP_arifle_M4A3_black",
			"CUP_arifle_M4A3_camo",
			//"CUP_arifle_M4A1_MOE_black",
			//"CUP_arifle_M4A1_MOE_wdl",
			//"CUP_arifle_M4A1_MOE_short_black",
			//"CUP_arifle_M4A1_MOE_short_wdl",
			"CUP_arifle_M4A1_standard_black",
			"CUP_arifle_M4A1_standard_wdl",
			"CUP_arifle_M4A1_standard_short_black",
			"CUP_arifle_M4A1_standard_short_wdl",
			//mk 18
			//"CUP_arifle_mk18_black",
			"CUP_arifle_mk18_m203_black",

			"CUP_arifle_SBR_black",
			"CUP_arifle_SBR_od",

			//"CUP_arifle_Sa58P",
			//"CUP_arifle_Sa58P_woodland",
			//"CUP_arifle_Sa58V",
			//"CUP_arifle_Sa58V_woodland",
			"CUP_arifle_Sa58RIS1",
			"CUP_arifle_Sa58RIS1_woodland",
			"CUP_arifle_Sa58RIS2_gl",
			"CUP_arifle_Sa58RIS2_gl_woodland",
			"CUP_arifle_Sa58RIS2",
			"CUP_arifle_Sa58RIS2_woodland",
			"CUP_arifle_Sa58P_frontris",
			"CUP_arifle_Sa58P_frontris_woodland",
			"CUP_arifle_Sa58P_v2",

			"CUP_arifle_Mk16_CQC_black",
			"CUP_arifle_Mk16_CQC_FG_black",
			"CUP_arifle_Mk16_CQC_AFG_black",
			"CUP_arifle_Mk16_CQC_SFG_black",
			"CUP_arifle_Mk16_CQC_EGLM_black",
			//"CUP_arifle_Mk16_STD_black",
			//"CUP_arifle_Mk16_STD_FG_black",
			//"CUP_arifle_Mk16_STD_AFG_black",
			//"CUP_arifle_Mk16_STD_SFG_black",
			//"CUP_arifle_Mk16_STD_EGLM_black",
			//"CUP_arifle_Mk16_SV_black",

			"CUP_arifle_Mk16_CQC_woodland",
			"CUP_arifle_Mk16_CQC_FG_woodland",
			"CUP_arifle_Mk16_CQC_AFG_woodland",
			"CUP_arifle_Mk16_CQC_SFG_woodland",
			"CUP_arifle_Mk16_CQC_EGLM_woodland",
			//"CUP_arifle_Mk16_STD_woodland",
			//"CUP_arifle_Mk16_STD_FG_woodland",
			//"CUP_arifle_Mk16_STD_AFG_woodland",
			//"CUP_arifle_Mk16_STD_SFG_woodland",
			//"CUP_arifle_Mk16_STD_EGLM_woodland",
			"CUP_arifle_Mk16_SV_woodland",

			"CUP_arifle_Mk17_CQC_Black",
			"CUP_arifle_Mk17_CQC_FG_black",
			"CUP_arifle_Mk17_CQC_SFG_black",
			"CUP_arifle_Mk17_CQC_EGLM_black",
			//"CUP_arifle_Mk17_STD_black",
			//"CUP_arifle_Mk17_STD_FG_black",
			//"CUP_arifle_Mk17_STD_SFG_black",
			//"CUP_arifle_Mk17_STD_EGLM_black",
			"CUP_arifle_Mk17_CQC_woodland",
			"CUP_arifle_Mk17_CQC_FG_woodland",
			"CUP_arifle_Mk17_CQC_SFG_woodland",
			"CUP_arifle_Mk17_CQC_EGLM_woodland",
			//"CUP_arifle_Mk17_STD_woodland",
			//"CUP_arifle_Mk17_STD_FG_woodland",
			//"CUP_arifle_Mk17_STD_SFG_woodland",
			//"CUP_arifle_Mk17_STD_EGLM_woodland",

			"CUP_arifle_Mk20_black",
			"CUP_arifle_Mk20_woodland",

			"CUP_arifle_HK_M27",
			"CUP_arifle_HK_M27_VFG",
			"CUP_arifle_HK_M27_AG36"

			//"CUP_arifle_XM8_Carbine",
			//"CUP_arifle_XM8_Carbine_FG",
			//"CUP_arifle_XM8_Carbine_GL",
			//"CUP_arifle_xm8_sharpshooter",
			//"CUP_arifle_xm8_SAW",
			//"CUP_arifle_XM8_Compact",
			//"CUP_arifle_XM8_Compact_Rail",
			//"CUP_arifle_XM8_Railed"
		};
	};
	////////////////////////////////////////////////////////////////////
	//  Weapons - Shotguns
	////////////////////////////////////////////////////////////////////
	class Shotguns
	{
		name = "Shotguns";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"Exile_Weapon_M1014",
			"CUP_sgun_AA12",
			"CUP_sgun_SPAS12"
		};
	};
	////////////////////////////////////////////////////////////////////
	//  Weapons - Sniper Rifles
	////////////////////////////////////////////////////////////////////
	class SniperRifles
	{
		name = "Sniper Rifles";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"arifle_MXM_Black_F",
			//"arifle_MXM_F",
			"srifle_DMR_01_F",
			"srifle_DMR_03_F",
			//"srifle_DMR_03_khaki_F",
			//"srifle_DMR_03_multicam_F",
			//"srifle_DMR_03_tan_F",
			//"srifle_DMR_03_woodland_F",
			"srifle_DMR_04_F",
			//"srifle_DMR_04_Tan_F",
			//"srifle_DMR_06_camo_F",
			//"srifle_DMR_06_olive_F",
			"srifle_EBR_F",
			//"Exile_Weapon_CZ550",
			//"Exile_Weapon_SVD",
			//"Exile_Weapon_SVDCamo",
			//"Exile_Weapon_VSSVintorez",
			//"Exile_Weapon_DMR",
			//"Exile_Weapon_LeeEnfield",
			"CUP_srifle_CZ750",
			"CUP_srifle_CZ550",
			"CUP_srifle_CZ550_rail",
			//"CUP_srifle_LeeEnfield",
			"CUP_srifle_LeeEnfield_rail",
			"CUP_srifle_M14_DMR",
			"CUP_srifle_DMR",
			"CUP_srifle_M14",
			"CUP_srifle_M24_wdl",
			"CUP_srifle_M24_blk",
			"CUP_srifle_M40A3",
			"CUP_srifle_RSASS_Black",
			"CUP_srifle_RSASS_WDL",
			"CUP_srifle_RSASS_WDLNet",
			//"CUP_srifle_RSASS_Dazzle",
			"CUP_srifle_RSASS_Jungle",
			//"CUP_srifle_SVD_wdl",
			"CUP_srifle_SVD_wdl_top_rail",
			//"CUP_srifle_VSSVintorez",
			"CUP_srifle_VSSVintorez_top_rail",
			//"CUP_srifle_VSSVintorez_VFG",
			"CUP_srifle_VSSVintorez_VFG_top_rail",
			//"CUP_srifle_VSSVintorez_flash",
			//"CUP_srifle_VSSVintorez_flash_top",
			//"CUP_SKS",
			"CUP_SKS_rail",
			"CUP_huntingrifle", /// ff checken.
			"CUP_srifle_Mk12SPR",
			"CUP_srifle_Mosin_Nagant",
			"CUP_srifle_L129A1",
			"CUP_srifle_L129A1_HG",
			"CUP_srifle_M110",
			"CUP_srifle_M110_black",
			"CUP_srifle_M110_woodland",
			"CUP_srifle_m110_kac",
			"CUP_srifle_m110_kac_black",
			"CUP_srifle_m110_kac_woodland",
			"CUP_srifle_Remington700",
			//Apex
			"srifle_DMR_07_blk_F",
			"srifle_DMR_07_hex_F",
			"srifle_DMR_07_ghex_F",			
		};
	};
	// Weapons
	class CUP_Weapons_SNIPERLOOTTABLE
	{
		name = "Sniperrifle LOOTTABLE";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
		items[] = 
		{
			//MAR 10
			"srifle_DMR_02_camo_F",
			"srifle_DMR_02_F",
			"srifle_DMR_02_sniper_F",
			//SIRUS
			"srifle_DMR_05_blk_F",
			"srifle_DMR_05_hex_F",
			"srifle_DMR_05_tan_f",
			//AS50
			"CUP_srifle_AS50",
			//"CUP_srifle_M107_Desert",
			"CUP_srifle_M107_Pristine",
			//"CUP_srifle_M107_Snow",
			"CUP_srifle_M107_Woodland",
			//"Exile_Weapon_m107",
			//Lynx
			"srifle_GM6_camo_F",
			"srifle_GM6_F",
			"srifle_GM6_ghex_F",
			//LAPUA
			"srifle_LRR_camo_F",
			"srifle_LRR_F",
			"srifle_LRR_tna_F",
			"CUP_srifle_AWM_wdl",
			"CUP_srifle_AWM_blk",
			"CUP_srifle_G22_wdl",
			"CUP_srifle_G22_blk",
			//KSVK
			"CUP_srifle_ksvk",
			//"Exile_Weapon_ksvk",
		};
	};
	////////////////////////////////////////////////////////////////
	// Weapons - Navid SPMG
	////////////////////////////////////////////////////////////////
	class NavidSPMG
	{
		name = "Navid & SPMG";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] = 
		{
			"MMG_01_hex_F",
			//"MMG_01_tan_F",
			//"150Rnd_93x64_Mag"
			"MMG_02_black_F",
			//"MMG_02_camo_F",
			//"MMG_02_sand_F"
			//"130Rnd_338_Mag"
		};
	};
	/////////////////////////////////////////////////////////
	// LAGO
	/////////////////////////////////////////////////////////
	class lagoGUN
	{
		name = "LAGO";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemacc_ca.paa";
		items[] =
		{
			"LAGO_Biken"
		};
	};
	class CUP_Weapons_GL1
	{
		name = "Grenade launcher";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
		items[] = 
		{
			"CUP_glaunch_M32",
			"CUP_glaunch_M79",
			"CUP_glaunch_Mk13",
			"CUP_glaunch_6G30"
		};
	};
	// Weapons
	class CUP_Weapons_RL1
	{
		name = "Rocket Launcher";
		icon = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
		items[] = 
		{
			"CUP_launch_MAAWS",
			"CUP_launch_Mk153Mod0",
			"CUP_launch_Mk153Mod0_blk",
			"CUP_launch_RPG7V"
		};
	};